//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLAmNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiHat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiHat()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.Playlist_ChiTiet = new HashSet<Playlist_ChiTiet>();
            this.TagVotes = new HashSet<TagVote>();
        }
    
        public int MaBaiHat { get; set; }
        public string TenBaiHat { get; set; }
        public string NguoiTrinhBay { get; set; }
        public string LinkYoutube { get; set; }
        public Nullable<int> NguoiUpload { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> TrangThaiDuyet { get; set; }
        public string GhiChuAdmin { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playlist_ChiTiet> Playlist_ChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagVote> TagVotes { get; set; }
    }
}
