//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLAmNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BinhLuan()
        {
            this.BinhLuanVotes = new HashSet<BinhLuanVote>();
        }
    
        public int MaBinhLuan { get; set; }
        public string NoiDung { get; set; }
        public int MaNguoiDung { get; set; }
        public Nullable<int> MaBaiHat { get; set; }
        public Nullable<int> MaPlaylist { get; set; }
        public Nullable<System.DateTime> NgayBinhLuan { get; set; }
    
        public virtual BaiHat BaiHat { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Playlist Playlist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuanVote> BinhLuanVotes { get; set; }
    }
}
