//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLAmNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuanVote
    {
        public int MaBinhLuan { get; set; }
        public int MaNguoiDung { get; set; }
        public Nullable<System.DateTime> NgayVote { get; set; }
        public bool IsUpvote { get; set; }
    
        public virtual BinhLuan BinhLuan { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
