//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLAmNhac.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLAmNhac_Web1Entities1 : DbContext
    {
        public QLAmNhac_Web1Entities1()
            : base("name=QLAmNhac_Web1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiHat> BaiHats { get; set; }
        public virtual DbSet<BinhLuan> BinhLuans { get; set; }
        public virtual DbSet<BinhLuanVote> BinhLuanVotes { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<Playlist> Playlists { get; set; }
        public virtual DbSet<Playlist_ChiTiet> Playlist_ChiTiet { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TagVote> TagVotes { get; set; }
        public virtual DbSet<TheoDoi> TheoDois { get; set; }
    }
}
