//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLAmNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Playlist_ChiTiet
    {
        public int MaPlaylist { get; set; }
        public int MaBaiHat { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public Nullable<int> ThuTu { get; set; }
    
        public virtual BaiHat BaiHat { get; set; }
        public virtual Playlist Playlist { get; set; }
    }
}
