//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLAmNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagVote
    {
        public int MaBaiHat { get; set; }
        public int MaTag { get; set; }
        public int MaNguoiDung { get; set; }
        public Nullable<System.DateTime> NgayVote { get; set; }
    
        public virtual BaiHat BaiHat { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
