//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLAmNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheoDoi
    {
        public int MaNguoiTheoDoi { get; set; }
        public int MaNgheSi { get; set; }
        public Nullable<System.DateTime> NgayTheoDoi { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
